version: "3.4"

services:
  bot:
    image: banochka_bot:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TG_TOKEN: ${TG_TOKEN}
        KINO_TOKEN: ${KINO_TOKEN}
    volumes:
      - ./
